### PR TITLE
Set the correct fsType for erofs when prefetching through the file list

### PR DESCRIPTION
**Pull request by salvete**
**What this PR does / why we need it**:

When prefetching using the file list, the default fsType is ext4, even if the file system on the virtual block device is actually erofs. This sets the correct fsType based on the file system type present on the virtual block device.

The corresponding overlaybd PR:
https://github.com/containerd/overlaybd/pull/344

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

**Review by hsiangkao — CHANGES_REQUESTED** [review]
`OverlayBDBlobFsType` shouldn't be used for turboOCI due to multiple fsmeta cases.

**Comment by salvete** [comment]
> `OverlayBDBlobFsType` shouldn't be used for turboOCI due to multiple fsmeta cases.

Done. Now for erofs, the fsType is determined by the superblock of the virtual block device.

**Comment by BigVan** [comment]
LGTM

**Review by WaberZhuang — APPROVED** [review]
LGTM

**Pull request merged**
