### PR TITLE
Update dependencies (containerd v2)

### PR DESCRIPTION
**Pull request by apostasie**
**What this PR does / why we need it**:

Hi folks.

This PR updates dependencies, with a specific focus on containerd (v2).

It also bumps the go version to align with ^, upgrades github actions and urfave (v2).

Please NOTE that currently this is swapping out `github.com/data-accelerator/zdfs` to `github.com/apostasie/zdfs` and should of course NOT be merged as-is. Evidently, as soon as the PR on zdfs gets through I will update this to make it ready (https://github.com/data-accelerator/zdfs/pull/3).

**Please check the following list**:
- [x] Does the affected code have corresponding tests, e.g. unit test, E2E test?
   - No new test
- [x] Does this change require a documentation update?
   - Golang version requirement has been updated
- [x]  Does this introduce breaking changes that would require an announcement or bumping the major version?
   - I believe so. Although there is nothing that should break API compatibility, this is a major change in dependencies.
- [x]  Do all new files have an appropriate license header?
  - n.a.

Let me know your thoughts.

Thanks a lot.

### CODE REVIEW

**Comment by apostasie** [comment]
@liulanzheng not quite sure why the CI would use go 1.19 (as I did upgrade to 1.22)?
Is the env GO_VERSION set outside of the action files?

Thanks.

**Comment by apostasie** [comment]
Rebased against latest main.

e2e still failing as they rely on go 1.19 apparently.

**Comment by liulanzheng** [comment]
@yuchen0cc It seems that the CI was using the script from the main branch instead of the script modified in the PR. How should this situation be handled?

**Comment by liulanzheng** [comment]
@apostasie After confirming with @yuchen0cc, to prevent potential attacks from CI, the CI runs the code from the target branch. Therefore, we have to merge the code first before running the new CI. Additionally, could we merge the zdfs first before merging this branch?

**Comment by apostasie** [comment]
> @apostasie After confirming with @yuchen0cc, to prevent potential attacks from CI, the CI runs the code from the target branch. Therefore, we have to merge the code first before running the new CI. Additionally, could we merge the zdfs first before merging this branch?

Thanks @liulanzheng !

For sure - we do need the zdfs PR merged first.
Akihiro just pinged someone over there, so, let's give it some time for them to react?

If you want, I can ping you back here once it is done and this one is updated to reflect that.

**Comment by apostasie** [comment]
Hey @liulanzheng 

zdfs PR got merged last night.

I just updated this here so that we are back on zdfs main instead of my fork (thanks to @AkihiroSuda help).

I guess this here is ready for review (or merge on a feature branch?)

Let me know if you need anything else here from me.

Thanks a lot!

**Review by liulanzheng — APPROVED** [review]
LGTM. Only involves dependency changes. It is recommended to merge first and then check the e2e results.

**Comment by liulanzheng** [comment]
All CI passed

**Comment by apostasie** [comment]
Thanks a lot @liulanzheng !

Appreciate the help.

**Pull request merged**
